### ISSUE TITLE
Kin2 -> Kin4 wallets are not available through kinEnvironment?.allAccountIds()?.callback on base:1.0.1 SDK

### ISSUE THREAD

**Issue by chitrang200889** [kinecosystem/kin-android#29]
Issue: Our app migrated from Kin2 to Kin4 so our existing major release is using base:0.4.5 which had support of KinStellarMainNetKin2 NetworkEnvironment. But it has been removed from base:1.0.1 SDK and forcing us to use NetworkEnvironment.MainNet that is for Kin3.

To understand the bug,

First, see the difference over here [NetworkEnvironment base:0.4.5 vs base:1.0.1](https://github.com/kinecosystem/kin-android/commit/70c1d2e10dc05c8e9be439a1ff234c644333d9b7#diff-e7d8e23f6dcb26ab2f090492e32cb72a2b93df0e8a420515fc418c5ccc0b8055), params of Kin2 KinStellarTestNetKin2, Kin2MainNetPassphrase and Kin2IssuerProd were removed. 

Second, KinFileStorage class has this line of [code](https://github.com/kinecosystem/kin-android/blob/408f0d453db3cd11205460d3fa19db8ce16a46dc/base/src/main/java/org/kin/sdk/base/storage/KinFileStorage.kt#L536), that creates directory based on networkPassphrase which is removed for Kin2 in base:1.0.1.

**Solution - 1 :** Revert the changes of NetworkEnvironment class so that it doesn't require major changes.

However,  it still requires rigorous testing as networkEnvironment.issuer was also being used in [KinServiceImpl class of base:0:4:5](https://github.com/kinecosystem/kin-android/blob/07dd33807f505ab9cb04e910760875d367c0b43e/base/src/main/java/org/kin/sdk/base/network/services/KinServiceImpl.kt#L274)

Also,  Kin2 related variables must be there in all the upcoming updates so we don't face this issue again in the future.

**Solution - 2:** base SDK reads all the wallets of Kin2 file system and re-stores them in Kin3 file system and we continue to use NetworkEnvironment.MainNet of Kin3. This is more preferable as we already have done minor release so small set of users wallet are stored in Kin3 file system. If not then users have to take backup of their QR code and reimport again to store wallet under kin2 file system.

**Comment by hitwill** [comment]
This should be related to the stellar artefacts that were removed

This line of code is creating sub directory based on networkPassphrase value
![image](https://user-images.githubusercontent.com/2501079/121619391-e11e2680-caab-11eb-8cd7-c6efe72b263b.png)
And since const val Kin2MainNetPassphrase = "Public Global Kin Ecosystem Network ; June 2018" has been removed from version 1.0.1
![image](https://user-images.githubusercontent.com/2501079/121619406-e7ac9e00-caab-11eb-9a98-a0b56cf62ffd.png)
![image](https://user-images.githubusercontent.com/2501079/121619423-ef6c4280-caab-11eb-856a-f1ad0dee155a.png)

(quoting previous discussion with @chitrang200889 chitrang200889)

**Comment by hitwill** [comment]
We'll look at this next week

**Comment by hitwill** [comment]
test
