### ISSUE TITLE
Unable to restore account from iOS (KeyPair enhancement required)

### ISSUE THREAD

**Issue by showered** [kinecosystem/kin-android#32]
It's currently impossible to backup on iOS and restore on Android.

The reason for this is because iOS stores and exports the `PrivateKey` but Android expects `Seed`.

You can currently only create a `KeyPair` on Android with the `fromSecretSeed()` method.

If we were to have a new method, `fromKeyPair` with `byte[] PublicKey` and `byte[] PrivateKey` as parameters, then this should hopefully enable cross-platform backup/restore. I tried to do it myself, but the byte arrays need transforming in to `EdDSAPublicKey` and `EdDSAPublicKey`, which is beyond my understanding I'm afraid.

Thank you.

**Comment by samdowd** [comment]
Spent some time on this. I was able to get a little further after learning about EdDSA, and I managed to create a keypair using an iOS backup. Unfortunately the entire Android implementation revolves around a `PrivateKey` that would be more accurately called `Seed` because it actually just stores the seed and turns it into a private key on demand. All functions that need the private key (notably signing) are structured to take the seed, private-key it (hash + some other stuff), and then do whatever they're doing from what I'm seeing.

You don't need the seed to do any of this, but because of the way things are set up right now, this is more of a structural change than I'd hoped.
