### ISSUE TITLE
kinAccount.buildTransaction() is processing memo incorrectly (compatibility mode)

### ISSUE THREAD

**Issue by showered** [kinecosystem/kin-android#5]
This is the Java code I have from legacy Android SDK:

```
Request<Transaction> buildTransactionRequest = kinAccount.buildTransaction(toAddress, amountInKin, fee, memo);
```

Previously this was returning a XDR that contains something that looked like this:

```
memo: [memoText]
text: 1-xnXb-b1d2ee9165304d5c [hex: MS14blhiLWIxZDJlZTkxNjUzMDRkNWM=]
```

But now it's returning a XDR that contains something that looks like this:

```
memo: [memoHash]
hash: ZDlhNDNiYWQwNzIxNDkzYgAAAAAAAAAAAAAAAAAAAAA=
```

The `1-xnXb-` prefix is missing. Also it is Base64 encoded, whereas previously it was plain text.

This means that I can't make any Whitelisted "spends" from my app with the `base-compat` installed.

Thanks in advance.

**Comment by kikengineering** [comment]
Hey thanks for this submission. The memo was sent as a stellar Memo.Hash instead of Memo.Text, which explains the encoding differences you were seeing. While this would not have affected whitelisting at all (since whitelisting is performed by adding an additional signature from a whitelisted wallet to the transaction envelope and does not depend on the stringified appId in a memo field) this was an oversight on our part. In the near future we are moving to a binary memo format and so we were always encoding using the stellar Memo.Hash type.

This has been corrected to use the Memo.Text type under the `:base-compat` library as you expect in version `0.1.6` released a few minutes ago.
